# Deploy: gcloud app deploy app.yaml --project owlrepo
runtime: nodejs22
entrypoint: node build

build_env_variables:
  PROJECT_ID: "owlrepo"
  PUBLIC_OWLREPO_URL: "https://api-v1-6jpxgj6jpa-uc.a.run.app"

automatic_scaling:
  max_instances: 3
  min_instances: 1
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  max_concurrent_requests: 80

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301